package me.buck.cloudmusic.bean

import me.buck.cloudmusic.bean.em.EmTitleColor

/*
{
  "banners": [
    {
      "pic": "http://p1.music.126.net/PeflBz0PFC8AnWIy8q33Vg==/109951165070235343.jpg",
      "targetId": 1454730043,
      "adid": null,
      "targetType": 1,
      "titleColor": "red",
      "typeTitle": "独家",
      "url": null,
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "1454730043",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": {
        "name": "赤伶",
        "id": 1454730043,
        "pst": 0,
        "t": 0,
        "ar": [
          {
            "id": 4130,
            "name": "李玉刚",
            "tns": [],
            "alias": []
          }
        ],
        "alia": [],
        "pop": 100,
        "st": 0,
        "rt": "",
        "fee": 8,
        "v": 3,
        "crbt": null,
        "cf": "",
        "al": {
          "id": 90729980,
          "name": "赤伶",
          "picUrl": "http://p1.music.126.net/0el5yaTEo3KjeJjL3ZXxmg==/109951165054951989.jpg",
          "tns": [],
          "pic_str": "109951165054951989",
          "pic": 109951165054951980
        },
        "dt": 300000,
        "h": {
          "br": 320000,
          "fid": 0,
          "size": 12001965,
          "vd": -36061
        },
        "m": {
          "br": 192000,
          "fid": 0,
          "size": 7201197,
          "vd": -33472
        },
        "l": {
          "br": 128000,
          "fid": 0,
          "size": 4800813,
          "vd": -31840
        },
        "a": null,
        "cd": "01",
        "no": 0,
        "rtUrl": null,
        "ftype": 0,
        "rtUrls": [],
        "djId": 0,
        "copyright": 0,
        "s_id": 0,
        "mark": 8192,
        "originCoverType": 0,
        "noCopyrightRcmd": null,
        "rtype": 0,
        "rurl": null,
        "mst": 9,
        "cp": 0,
        "mv": 0,
        "publishTime": 0,
        "privilege": {
          "id": 1454730043,
          "fee": 8,
          "payed": 0,
          "st": 0,
          "pl": 128000,
          "dl": 0,
          "sp": 7,
          "cp": 1,
          "subp": 1,
          "cs": false,
          "maxbr": 999000,
          "fl": 128000,
          "toast": false,
          "flag": 68,
          "preSell": false
        }
      },
      "bannerId": "1592401870450242",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.695451.2014121717.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    },
    {
      "pic": "http://p1.music.126.net/VoZgqTw8mgqBe1vjVtvLvA==/109951165071676444.jpg",
      "targetId": 0,
      "adid": null,
      "targetType": 3000,
      "titleColor": "blue",
      "typeTitle": "独家策划",
      "url": "https://music.163.com/m/at/5ec663bf66385ede43ce133b",
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "0",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": null,
      "bannerId": "1592470985701663",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.702449.2014120081.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    },
    {
      "pic": "http://p1.music.126.net/Vtf5l_B70UzZ_M86vTJueA==/109951165071135303.jpg",
      "targetId": 1369649924,
      "adid": null,
      "targetType": 1,
      "titleColor": "red",
      "typeTitle": "独家",
      "url": null,
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "1369649924",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": {
        "name": "山妖",
        "id": 1369649924,
        "pst": 0,
        "t": 0,
        "ar": [
          {
            "id": 13288117,
            "name": "小星星Aurora",
            "tns": [],
            "alias": []
          },
          {
            "id": 961055,
            "name": "周玥",
            "tns": [],
            "alias": []
          }
        ],
        "alia": [],
        "pop": 100,
        "st": 0,
        "rt": "",
        "fee": 8,
        "v": 22,
        "crbt": null,
        "cf": "",
        "al": {
          "id": 79563943,
          "name": "山妖",
          "picUrl": "http://p1.music.126.net/y8M2B3moftkO1fRPcTvbOA==/109951165050129476.jpg",
          "tns": [],
          "pic_str": "109951165050129476",
          "pic": 109951165050129470
        },
        "dt": 265331,
        "h": {
          "br": 320000,
          "fid": 0,
          "size": 10615725,
          "vd": 10495
        },
        "m": {
          "br": 192000,
          "fid": 0,
          "size": 6369453,
          "vd": 13046
        },
        "l": {
          "br": 128000,
          "fid": 0,
          "size": 4246317,
          "vd": 14591
        },
        "a": null,
        "cd": "01",
        "no": 1,
        "rtUrl": null,
        "ftype": 0,
        "rtUrls": [],
        "djId": 0,
        "copyright": 0,
        "s_id": 0,
        "mark": 8192,
        "originCoverType": 0,
        "noCopyrightRcmd": null,
        "rtype": 0,
        "rurl": null,
        "mst": 9,
        "cp": 1416756,
        "mv": 0,
        "publishTime": 0,
        "privilege": {
          "id": 1369649924,
          "fee": 8,
          "payed": 0,
          "st": 0,
          "pl": 128000,
          "dl": 0,
          "sp": 7,
          "cp": 1,
          "subp": 1,
          "cs": false,
          "maxbr": 999000,
          "fl": 128000,
          "toast": false,
          "flag": 68,
          "preSell": false
        }
      },
      "bannerId": "1592448215473478",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.700479.2014060403.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    },
    {
      "pic": "http://p1.music.126.net/zaxT66iSyAxYfl_-BTpeVQ==/109951165070261974.jpg",
      "targetId": 1445761206,
      "adid": null,
      "targetType": 1,
      "titleColor": "red",
      "typeTitle": "热歌推荐",
      "url": null,
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "1445761206",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": {
        "name": "雨爱",
        "id": 1445761206,
        "pst": 0,
        "t": 0,
        "ar": [
          {
            "id": 12157330,
            "name": "周星星",
            "tns": [],
            "alias": []
          }
        ],
        "alia": [],
        "pop": 100,
        "st": 0,
        "rt": "",
        "fee": 8,
        "v": 4,
        "crbt": null,
        "cf": "",
        "al": {
          "id": 88986638,
          "name": "雨爱",
          "picUrl": "http://p1.music.126.net/3aI-tMbFvqPvD1AnsaineQ==/109951164962643372.jpg",
          "tns": [],
          "pic_str": "109951164962643372",
          "pic": 109951164962643380
        },
        "dt": 251428,
        "h": {
          "br": 320000,
          "fid": 0,
          "size": 10059276,
          "vd": -57974
        },
        "m": {
          "br": 192000,
          "fid": 0,
          "size": 6035583,
          "vd": -55409
        },
        "l": {
          "br": 128000,
          "fid": 0,
          "size": 4023737,
          "vd": -53809
        },
        "a": null,
        "cd": "01",
        "no": 1,
        "rtUrl": null,
        "ftype": 0,
        "rtUrls": [],
        "djId": 0,
        "copyright": 0,
        "s_id": 0,
        "mark": 8192,
        "originCoverType": 0,
        "noCopyrightRcmd": null,
        "rtype": 0,
        "rurl": null,
        "mst": 9,
        "cp": 1416619,
        "mv": 0,
        "publishTime": 0,
        "privilege": {
          "id": 1445761206,
          "fee": 8,
          "payed": 0,
          "st": 0,
          "pl": 128000,
          "dl": 0,
          "sp": 7,
          "cp": 1,
          "subp": 1,
          "cs": false,
          "maxbr": 999000,
          "fl": 128000,
          "toast": false,
          "flag": 68,
          "preSell": false
        }
      },
      "bannerId": "1592402514052167",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.698463.2014059535.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    },
    {
      "pic": "http://p1.music.126.net/A85HH9XF1oxLbU025j88Xg==/109951165070279088.jpg",
      "targetId": 0,
      "adid": null,
      "targetType": 3000,
      "titleColor": "blue",
      "typeTitle": "数字专辑",
      "url": "https://music.163.com/store/newalbum/detail?id=90727327",
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "0",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": null,
      "bannerId": "1592402650976309",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.700476.1450437114.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    },
    {
      "pic": "http://p1.music.126.net/iKQFl3HJjJcmOKLnMSZfzA==/109951165071675817.jpg",
      "targetId": 90229399,
      "adid": null,
      "targetType": 10,
      "titleColor": "red",
      "typeTitle": "新碟首发",
      "url": null,
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "90229399",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": null,
      "bannerId": "1592470823016625",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.702452.2013907422.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    },
    {
      "pic": "http://p1.music.126.net/aiMm6CUTIR-oJSiVI1HXJA==/109951165070314521.jpg",
      "targetId": 1456170189,
      "adid": null,
      "targetType": 1,
      "titleColor": "red",
      "typeTitle": "独家",
      "url": null,
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "1456170189",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": {
        "name": "顾家 (同居版)",
        "id": 1456170189,
        "pst": 0,
        "t": 0,
        "ar": [
          {
            "id": 3701,
            "name": "黎明",
            "tns": [],
            "alias": []
          }
        ],
        "alia": [],
        "pop": 5,
        "st": 0,
        "rt": "",
        "fee": 8,
        "v": 3,
        "crbt": null,
        "cf": "",
        "al": {
          "id": 91096320,
          "name": "顾家",
          "picUrl": "http://p1.music.126.net/JrYTbyOKFtz4PM3dRsxLLw==/109951165069082307.jpg",
          "tns": [],
          "pic_str": "109951165069082307",
          "pic": 109951165069082300
        },
        "dt": 229914,
        "h": {
          "br": 320000,
          "fid": 0,
          "size": 9198765,
          "vd": -49969
        },
        "m": {
          "br": 192000,
          "fid": 0,
          "size": 5519277,
          "vd": -47370
        },
        "l": {
          "br": 128000,
          "fid": 0,
          "size": 3679533,
          "vd": -45721
        },
        "a": null,
        "cd": "01",
        "no": 1,
        "rtUrl": null,
        "ftype": 0,
        "rtUrls": [],
        "djId": 0,
        "copyright": 0,
        "s_id": 0,
        "mark": 8192,
        "originCoverType": 0,
        "noCopyrightRcmd": null,
        "rtype": 0,
        "rurl": null,
        "mst": 9,
        "cp": 1416004,
        "mv": 0,
        "publishTime": 0,
        "privilege": {
          "id": 1456170189,
          "fee": 8,
          "payed": 0,
          "st": 0,
          "pl": 128000,
          "dl": 0,
          "sp": 7,
          "cp": 1,
          "subp": 1,
          "cs": false,
          "maxbr": 999000,
          "fl": 128000,
          "toast": false,
          "flag": 68,
          "preSell": false
        }
      },
      "bannerId": "1592403357152124",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.701471.2013970126.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    },
    {
      "pic": "http://p1.music.126.net/8hfVATclXmnPBBCzY2db1g==/109951165070319518.jpg",
      "targetId": 1454659226,
      "adid": null,
      "targetType": 1,
      "titleColor": "red",
      "typeTitle": "独家",
      "url": null,
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "1454659226",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": {
        "name": "工业时代",
        "id": 1454659226,
        "pst": 0,
        "t": 0,
        "ar": [
          {
            "id": 12136078,
            "name": "葛东琪",
            "tns": [],
            "alias": []
          }
        ],
        "alia": [],
        "pop": 5,
        "st": 0,
        "rt": "",
        "fee": 8,
        "v": 1,
        "crbt": null,
        "cf": "",
        "al": {
          "id": 79886335,
          "name": "第二街区",
          "picUrl": "http://p1.music.126.net/CDhYcShQKH2VAMENuCxWWQ==/109951164166513349.jpg",
          "tns": [],
          "pic_str": "109951164166513349",
          "pic": 109951164166513340
        },
        "dt": 204576,
        "h": {
          "br": 320000,
          "fid": 0,
          "size": 8185774,
          "vd": -19208
        },
        "m": {
          "br": 192000,
          "fid": 0,
          "size": 4911482,
          "vd": -16690
        },
        "l": {
          "br": 128000,
          "fid": 0,
          "size": 3274336,
          "vd": -15353
        },
        "a": null,
        "cd": "01",
        "no": 7,
        "rtUrl": null,
        "ftype": 0,
        "rtUrls": [],
        "djId": 0,
        "copyright": 0,
        "s_id": 0,
        "mark": 0,
        "originCoverType": 0,
        "noCopyrightRcmd": null,
        "rtype": 0,
        "rurl": null,
        "mst": 9,
        "cp": 0,
        "mv": 0,
        "publishTime": 0,
        "privilege": {
          "id": 1454659226,
          "fee": 8,
          "payed": 0,
          "st": 0,
          "pl": 128000,
          "dl": 0,
          "sp": 7,
          "cp": 1,
          "subp": 1,
          "cs": false,
          "maxbr": 999000,
          "fl": 128000,
          "toast": false,
          "flag": 64,
          "preSell": false
        }
      },
      "bannerId": "1592403467166111",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.695460.1450444870.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    },
    {
      "pic": "http://p1.music.126.net/aQ7U386FaQmixYSPffnnUA==/109951165070323131.jpg",
      "targetId": 1456066520,
      "adid": null,
      "targetType": 1,
      "titleColor": "red",
      "typeTitle": "独家",
      "url": null,
      "adurlV2": null,
      "exclusive": false,
      "monitorImpress": null,
      "monitorClick": null,
      "monitorType": null,
      "monitorImpressList": [],
      "monitorClickList": [],
      "monitorBlackList": null,
      "extMonitor": null,
      "extMonitorInfo": null,
      "adSource": null,
      "adLocation": null,
      "encodeId": "1456066520",
      "program": null,
      "event": null,
      "video": null,
      "dynamicVideoData": null,
      "song": {
        "name": "summer time",
        "id": 1456066520,
        "pst": 0,
        "t": 0,
        "ar": [
          {
            "id": 1217008,
            "name": "曾雪雅",
            "tns": [],
            "alias": []
          }
        ],
        "alia": [],
        "pop": 90,
        "st": 0,
        "rt": "",
        "fee": 8,
        "v": 3,
        "crbt": null,
        "cf": "",
        "al": {
          "id": 91072487,
          "name": "summer time ",
          "picUrl": "http://p1.music.126.net/38Wx-iTEKfmo0z8aiP0XxA==/109951165068132510.jpg",
          "tns": [],
          "pic_str": "109951165068132510",
          "pic": 109951165068132510
        },
        "dt": 184436,
        "h": {
          "br": 320000,
          "fid": 0,
          "size": 7379565,
          "vd": -22430
        },
        "m": {
          "br": 192000,
          "fid": 0,
          "size": 4427757,
          "vd": -19838
        },
        "l": {
          "br": 128000,
          "fid": 0,
          "size": 2951853,
          "vd": -18146
        },
        "a": null,
        "cd": "01",
        "no": 0,
        "rtUrl": null,
        "ftype": 0,
        "rtUrls": [],
        "djId": 0,
        "copyright": 0,
        "s_id": 0,
        "mark": 128,
        "originCoverType": 0,
        "noCopyrightRcmd": null,
        "rtype": 0,
        "rurl": null,
        "mst": 9,
        "cp": 0,
        "mv": 0,
        "publishTime": 0,
        "privilege": {
          "id": 1456066520,
          "fee": 8,
          "payed": 0,
          "st": 0,
          "pl": 128000,
          "dl": 0,
          "sp": 7,
          "cp": 1,
          "subp": 1,
          "cs": false,
          "maxbr": 999000,
          "fl": 128000,
          "toast": false,
          "flag": 65,
          "preSell": false
        }
      },
      "bannerId": "1592403607318543",
      "alg": null,
      "scm": "1.music-homepage.homepage_banner_force.banner.695461.2014058543.null",
      "requestId": "",
      "showAdTag": true,
      "pid": null,
      "showContext": null,
      "adDispatchJson": null
    }
  ],
  "code": 200
}
*/

data class BannerResult(
    val banners: List<Banner>,
    val code: Int
)

data class Banner(
    val pic: String,
    val url: String?,
    val song: Song?,
    val targetId: Int,
    val targetType: Int,
    val titleColor: EmTitleColor,
    val typeTitle: String,
    val adDispatchJson: Any,
    val adLocation: Any,
    val adSource: Any,
    val adid: Any,
    val adurlV2: Any,
    val alg: Any,
    val bannerId: String,
    val dynamicVideoData: Any,
    val encodeId: String,
    val event: Any,
    val exclusive: Boolean,
    val extMonitor: Any,
    val extMonitorInfo: Any,
    val monitorBlackList: Any,
    val monitorClick: Any,
    val monitorClickList: List<Any>,
    val monitorImpress: Any,
    val monitorImpressList: List<Any>,
    val monitorType: Any,
    val pid: Any,
    val program: Any,
    val requestId: String,
    val scm: String,
    val showAdTag: Boolean,
    val showContext: Any,
    val video: Any
)

data class Song(
    val a: Any,
    val al: Al,
    val alia: List<Any>,
    val ar: List<Ar>,
    val cd: String,
    val cf: String,
    val copyright: Int,
    val cp: Int,
    val crbt: Any,
    val djId: Int,
    val dt: Int,
    val fee: Int,
    val ftype: Int,
    val h: H,
    val id: Int,
    val l: L,
    val m: M,
    val mark: Int,
    val mst: Int,
    val mv: Int,
    val name: String,
    val no: Int,
    val noCopyrightRcmd: Any,
    val originCoverType: Int,
    val pop: Int,
    val privilege: Privilege,
    val pst: Int,
    val publishTime: Long,
    val rt: String,
    val rtUrl: Any,
    val rtUrls: List<Any>,
    val rtype: Int,
    val rurl: Any,
    val s_id: Int,
    val st: Int,
    val t: Int,
    val v: Int
)

data class Al(
    val id: Int,
    val name: String,
    val pic: Long,
    val picUrl: String,
    val pic_str: String,
    val tns: List<Any>
)

data class Ar(
    val alias: List<Any>,
    val id: Int,
    val name: String,
    val tns: List<Any>
)

data class H(
    val br: Int,
    val fid: Int,
    val size: Int,
    val vd: Int
)

data class L(
    val br: Int,
    val fid: Int,
    val size: Int,
    val vd: Int
)

data class M(
    val br: Int,
    val fid: Int,
    val size: Int,
    val vd: Int
)

data class Privilege(
    val cp: Int,
    val cs: Boolean,
    val dl: Int,
    val fee: Int,
    val fl: Int,
    val flag: Int,
    val id: Int,
    val maxbr: Int,
    val payed: Int,
    val pl: Int,
    val preSell: Boolean,
    val sp: Int,
    val st: Int,
    val subp: Int,
    val toast: Boolean
)